# Este arquivo diz ao Netlify onde encontrar nossas funções de backend.
[functions]
  directory = "netlify/functions/"
  # Remova ou comente a linha abaixo para que o Netlify use o bundler padrão do Node.js
  # node_bundler = "esbuild"

# Esta regra redireciona as chamadas para nossas funções.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
