# Este arquivo diz ao Netlify onde encontrar nossas funções de backend.
[functions]
  directory = "netlify/functions/"
  # A linha 'node_bundler = "esbuild"' foi removida ou comentada para resolver o erro de importação.

# Esta regra redireciona as chamadas para nossas funções.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

